name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for required secrets
      run: |
        if [ -z "${{ secrets.SERVER_HOST }}" ]; then echo "ERROR: SERVER_HOST secret is not set."; exit 1; fi
        if [ -z "${{ secrets.SERVER_USER }}" ]; then echo "ERROR: SERVER_USER secret is not set."; exit 1; fi
        if [ -z "${{ secrets.SERVER_PORT }}" ]; then echo "ERROR: SERVER_PORT secret is not set."; exit 1; fi
        if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then echo "ERROR: SERVER_SSH_KEY secret is not set."; exit 1; fi
        echo "All required secrets are present."

    - name: Deploy with rsync
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -p ${{ secrets.SERVER_PORT }} -i private_key.pem -o StrictHostKeyChecking=no" \
          --exclude '.git/' \
          --exclude '.gitignore' \
          --exclude '.pytest_cache/' \
          --exclude '.venv/' \
          --exclude 'tests/' \
          --exclude 'doc/' \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/sao_paulo/
